version: '3.9'
services:

  server:
    build: .
    depends_on:
      - postgres
    ports:
      - "8085:8080"


  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
